language: node_js
sudo: false
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "node_modules/.bin/webpack --config test/webpack.config.js --output-path=test/tmp --output-filename=bundle.js"
  - "node_modules/.bin/testem ci -l firefox"
