language: node_js
sudo: false
node_js:
  - "4"
env:
  - WEBPACK_VERSION=1.13.1 WEBPACK_DEV_SERVER_VERSION=1.7.0 MOCHA_LOADER=0.7.1
  - WEBPACK_VERSION=2.2.1 WEBPACK_DEV_SERVER_VERSION=2.4.1 MOCHA_LOADER=1.0.0
matrix:
  include:
    - node_js: "0.12"
      env: WEBPACK_VERSION=1.13.1 WEBPACK_DEV_SERVER_VERSION=1.7.0 MOCHA_LOADER=0.7.1
    - node_js: "0.10"
      env: WEBPACK_VERSION=1.13.1 WEBPACK_DEV_SERVER_VERSION=1.7.0 MOCHA_LOADER=0.7.1
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - npm rm webpack webpack-dev-server mocha-loader
  - npm install webpack@$WEBPACK_VERSION webpack-dev-server@$WEBPACK_DEV_SERVER_VERSION mocha-loader@$MOCHA_LOADER
script:
  - "node_modules/.bin/webpack --config test/webpack.config.js --output-path=test/tmp --output-filename=bundle.js"
  - "node_modules/.bin/testem ci -l firefox"
